name: CI/CD - Full Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: quizdb
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    defaults:
      run:
        working-directory: ./quiz-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean install -DskipTests

      - name: Run backend tests
        run: mvn test

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: build-and-test-backend
    defaults:
      run:
        working-directory: ./quiz
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show quiz folder contents (debug)
        run: ls -la

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        run: docker build -t myapp-backend:latest ./quiz-backend

      - name: Build frontend Docker image
        run: docker build -t myapp-frontend:latest ./quiz

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: docker compose -f docker-compose.prod.yml up -d

      - name: Print deployment status
        run: docker ps
